# Generated by Django 4.1.5 on 2023-10-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoalChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_name', models.CharField(max_length=30)),
                ('gram', models.IntegerField()),
                ('calorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbs', models.IntegerField(default=40)),
                ('protein', models.IntegerField(default=30)),
                ('fat', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=250)),
                ('image', models.URLField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weight', models.FloatField()),
                ('goal_weight', models.FloatField()),
                ('week_goal_to_lose_or_gain', models.IntegerField()),
                ('calorie_goal', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriecounter.activitychoices')),
                ('nutrition_goal', models.ForeignKey(default=1500, on_delete=django.db.models.deletion.CASCADE, to='caloriecounter.nutrition')),
                ('your_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriecounter.goalchoices')),
            ],
        ),
    ]
